memory_limit = 5G
upload_max_filesize = 1G
post_max_size = 2G
;date.timezone = "America/New_York"
date.timezone = "Asia/Yekaterinburg"
max_execution_time = 300

opcache.enable_cli=On
;opcache.jit=tracing
opcache.jit=1205
opcache.jit_buffer_size=128M
