services:
    php_contact:
        build:
            context: php_contact
        volumes:
            - .:/var/www/symfony
            - ./docker-php.ini:/usr/local/etc/php/conf.d/docker-php.ini:ro
        environment:
            PHP_IDE_CONFIG: serverName=localhost
        extra_hosts:
            - "host.docker.internal:host-gateway"
        networks:
            - symfony_contact
        depends_on:
            - dbcon
            - rabbitmqcon

    dbcon:
        image: postgres:16-alpine
        restart: always
        environment:
            POSTGRES_DB: symfony_db
            POSTGRES_USER: symfony_user
            POSTGRES_PASSWORD: symfony_password
        ports:
            - "5438:5432"
        volumes:
            - db_data:/var/lib/postgresql/data
        networks:
            - symfony_contact

    rabbitmqcon:
        image: rabbitmq:3-management-alpine
        restart: always
        ports:
            - "5682:5672"
            - "15862:15672"
        environment:
            RABBITMQ_DEFAULT_USER: symfony_user
            RABBITMQ_DEFAULT_PASS: symfony_password
        volumes:
            - rabbitmq_data:/var/lib/rabbitmq
        networks:
            - symfony_contact
#            - external_network
        healthcheck:
            test: [ "CMD", "rabbitmq-diagnostics", "-q", "ping" ]
            interval: 30s
            timeout: 10s
            retries: 5

    nginx_contact:
        image: nginx:alpine
        ports:
            - "8090:80"
        volumes:
            - .:/var/www/symfony
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
        networks:
            - symfony_contact
        depends_on:
            - php_contact

volumes:
    db_data:
    rabbitmq_data:

networks:
    symfony_contact:
        driver: bridge
